language: python
python:
  - 2.7

install:
  - pip install -r src/crweb/requirements.txt
  - pip install -r src/crbridge/requirements.txt
  - pip install -r src/cram/requirements.txt

services:
  - redis-server

before_script:
  - sudo add-apt-repository ppa:rethinkdb/ppa --force-yes -y
  - sudo apt-get update -q
  - sudo apt-get install rethinkdb
  - rethinkdb
  - rethinkdb admin set auth cloudroutes
  - python src/crweb/web.py instance/crweb.cfg.default

script:
  - python src/crweb/tests.py
